# Site settings
title: Midwest Coder Blog
email: 
description: > # this means to ignore newlines until "baseurl:"
  Hello, this is a test blog.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: 
github_username:  zerasolar

# Build settings
markdown: redcarpet
